# Generated by Django 3.1.12 on 2023-05-02 04:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='room',
            old_name='creted',
            new_name='created',
        ),
    ]
